import { StyleSheet } from "react-native";
import colors from "../constants/colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: colors.primary,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    shadowColor: colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700",
  },
  filterButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    borderColor: colors.border,
    borderWidth: 1,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  searchInput: {
    marginLeft: 10,
    flex: 1,
    fontSize: 16,
    color: colors.textPrimary,
  },
  map: {
    flex: 1,
  },
  customMarker: {
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 25,
    width: 50,
    height: 50,
    overflow: "hidden",
  },
  markerImage: {
    width: "100%",
    height: "100%",
  },
  agentList: {
    position: "absolute",
    bottom: 100,
    width: "100%",
    paddingLeft: 10,
  },
  agentCard: {
    backgroundColor: colors.card,
    marginRight: 12,
    borderRadius: 16,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  agentImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
  },
  agentName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  footerButtonWrapper: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  findButton: {
    backgroundColor: colors.accent,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  findButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
});

export default styles;
